### ISSUE TITLE
golang.zx2c4.com/wireguard/go.mod at revision v0.0.20200320: unknown revision v0.0.20200320

### ISSUE THREAD

**Issue by ddevault** [yggdrasil-network/yggdrasil-go#759]
Seems like an issue with the module configuration for yggdrasil. Affects 0.3.15.

```
go: golang.zx2c4.com/wireguard@v0.0.20200320: reading golang.zx2c4.com/wireguard/go.mod at revision v0.0.20200320: unknown revision v0.0.20200320
```

**Comment by ddevault** [comment]
This is reproducible with the new release, only the error message is somewhat different:

```
go: golang.zx2c4.com/wireguard@v0.0.0-20210306175010-7e3b8371a1bf: invalid version: unknown revision 7e3b8371a1bf
```

I'm not sure how releases keep being shipped without addressing the broken build.

**Comment by neilalexander** [comment]
Which Go version are you using? I have yet to be able to reproduce this.

**Comment by ddevault** [comment]
Go 1.16.2.

**Comment by ddevault** [comment]
Hm, a colleague is unable to reproduce this as well. I'll look into it myself later on.

**Comment by neilalexander** [comment]
Not entirely sure what's going on, but my machine and CI seem to be OK. I've heard before of people having problems fetching Go dependencies with specific versions of Git?
```
imac:yggdrasil-go neilalexander$ go clean -cache -modcache -i -r

imac:yggdrasil-go neilalexander$ go build -a ./cmd/yggdrasil
go: downloading github.com/gologme/log v1.2.0
go: downloading github.com/hashicorp/go-syslog v1.0.0
go: downloading github.com/hjson/hjson-go v3.1.0+incompatible
go: downloading github.com/kardianos/minwinsvc v1.0.0
go: downloading github.com/mitchellh/mapstructure v1.4.1
go: downloading golang.org/x/text v0.3.6-0.20210220033129-8f690f22cf1c
go: downloading golang.org/x/crypto v0.0.0-20210220033148-5ea612d1eb83
go: downloading github.com/Arceliar/phony v0.0.0-20210209235338-dde1a8dca979
go: downloading golang.org/x/net v0.0.0-20210226172049-e18ecbb05110
go: downloading golang.org/x/sys v0.0.0-20210305230114-8fe3ee5dd75b
go: downloading golang.zx2c4.com/wireguard v0.0.0-20210306175010-7e3b8371a1bf

imac:yggdrasil-go neilalexander$ go version
go version go1.16 darwin/amd64

imac:~ neilalexander$ git version
git version 2.24.3 (Apple Git-128)
```

**Comment by ddevault** [comment]
Can you reproduce with GOPROXY=direct?

**Comment by neilalexander** [comment]
I've been able to reproduce with `GOPROXY=direct`, yes, which makes me wonder if the Wireguard guys are rebasing/removing commits or something. :/

This was supposed to be pinned to a tag, but it looks like that's gone too.

**Comment by ddevault** [comment]
That sounds plausible. Re-opening, though it might be wireguard's problem.

The only thing that yggdrasil uses from wireguard is their Linux tun wrapper, right? I'm pretty sure that's a couple hundred lines of code at most. Could be vendored.

**Comment by 5KS** [comment]
Saw similar on Fedora.  NixOS works, i think due to snapshots of the Go repos.

Solved by:
1. removed all **require**-lines inside go.mod
2. ran `go mod tidy`

**Comment by neilalexander** [comment]
I don’t expect this is still a problem in v0.4.0 but please reopen if it is.
